name: trigger-ci
run-name: ${{ github.actor }} has triggered ci update
on:
  push:
    branches:
      - "dev"

jobs:
  trigger-ci-update:
    runs-on: ubuntu-latest
    steps:
      - name: API Access
        run: curl -X POST --fail -F token=${{ secrets.GITLAB_PIPELINE_TRIGGER_TOKEN }} -F "ref=$TARGET_BRANCH" -F "variables[SUB_BRANCH]=$THIS_BRANCH" ${{ secrets.GITLAB_PIPELINE_URL }} > dump.txt && rm dump.txt
        env:
          TARGET_BRANCH: dev
          THIS_BRANCH: dev